### ISSUE TITLE
Help understanding traffic flow

### ISSUE THREAD

**Issue by erdii** [containous/maesh#245]
Traffic flow is described as:
![image](https://user-images.githubusercontent.com/5539202/65223542-bfa02e80-dac1-11e9-8b7e-4ffcd04bae5a.png)

But the rendered templates suggest, that a "plain old" ClusterIP k8s service is used to route traffic into the data-plane (traefik daemonset). Doesn't that imply, that we absolutely can NOT guarantee, that traffic gets sent to the traefik-pod on the same node? A service will route the traffic to SOME traefik-pod on SOME node, right?

Edit: typo and replaced wrong flow image

**Comment by SantoDE** [comment]
Hello @erdii,

you are correct. Services exposed via ClusterIP will be assigned traffic by kube-proxy based on the round robin algorithm.

This image has been created in order to make the traffic flow better visible und understandable, even tough it might not be 100% accurate. However, it helps in showing the concept behind it :)

As we want maesh to be non-invasive, we're not aware of a solution to make that flow 100% guaranteed. One possible option would be to set the kube-proxy into VPS mode, however, we wont take that cluster-wide actions.

**Comment by erdii** [comment]
Hey @SantoDE! Thank you for your answer.

I really like the idea of a non-invasive service-mesh that only deploys one agent per node, but the ClusterIP load-balancing basically circumvents the whole idea behind a service-mesh.

Say: I want to secure my "in-cluster" pod-to-pod communication with tls and decide to offload tls handling to maesh. Now I have a false sense of security, because I think, that "inter-node" pod-communication is TLS secured, but there can happen one "cleartext" hop to another node.

Maybe you could expose the local node ip to a mesh-consumer via fieldRef to "status.hostIP" and expose maesh via host-network? This, too is a hack but it would ensure that "inter-node" mesh traffik passes through the local traefik instance.

status.hostIP example: https://stackoverflow.com/a/57325211

**Comment by SantoDE** [comment]
Thanks for your feedback and suggestions @erdii.

I'll have a look and take it into account. Thanks a lot!
