### ISSUE TITLE
Update quickstart guide with a demo example (whoami based)

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#323]
#### Proposal

 Our quickstart guide should have a demo example that simply shows how to install and use Maesh with a one-pod app.

**Comment by jlevesy** [comment]
I'll take care of this

**Comment by dtomcej** [comment]
Awesome.

**Comment by riker09** [comment]
Can you please extend the example to either

* with SMI enabled, or
* with more than just `traffic-type` and `retry-attempts`.

Perhaps I don't understand what a Service Mesh is. Let me describe what I currently have and what I'm trying to achive.

Right now I'm developing a microservice app that consists of 20+ different microservices. For (local) development we decided to use Docker Swarm. Initially we thought we can use Swarm for production as well but due to recent events have decided to switch to Kubernetes.

Our application has a Caddy webserver as the web-facing part. Caddy takes care of certficate managment via Let's Encrypt and some basic rewriting. The next part of the chain is Traefik (v1.7) which we use to route traffic to the different parts of our application (mostly via path regex matching). The configuration provider for that is Consul KV.

I always trying to reduce dependencies to the minimum and would love to see an all-in-one solution where the Traefik (v2.x) in the Maesh Service Mesh handles everything. Am I completely off the track here or do you think this is the way I should go? I'm not asking for a step-by-step tutorial, a simple "do" or "don't" would be enough. I hope I can figure out the remains from there. :slightly_smiling_face:

**Comment by SantoDE** [comment]
Hey hey,

I'm not sure I understand your setup correctly, therefore I'll try to explain in a more generell matter.

You can use Maesh as a service-mesh inside your cluster, to manage connections between your 20+ microservices. So everytime one of your microservices calls another one, that connection can go through Maesh. That's when the annotations (`traffic-type` and `retry-attempts`) come into play.

For the Caddy part, I can't really follow you :) Caddy hosts your web-frontend then I guess? What do you use as Ingress Controller? That's what you could use Traefik v2.x for. However, that would be seperate instances from the Maesh one.

Does that make sense?

**Comment by riker09** [comment]
Hello @SantoDE  Yes, this makes perfect sense now. Thank for your explanation.

I was hoping I could use the Service Mesh as replacement for my current setup but I see now that it solves a different kind of problem. Regarding your question on what ingress controller I'm currently using: None. But that will change now. :grinning:
