### ISSUE TITLE
Review CI_TIMEOUT_MULTIPLIER

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#476]
#### Proposal

Currently many devs have to use the CI_TIMEOUT_MULTIPLIER to allow the tests to pass on their workstations.

If the CI needs more time, and the devs workstations all need more time, do we need to use this multiplier?

#### Background

The CI_TIMEOUT_MULTIPLIER was used when workstations were fast, and the CI was slow....but that should be revisited, and removed if not needed.

**Comment by jspdown** [comment]
I think we have to keep this multiplier. When writing an integration test we should make sure it runs on the CI with no multiplier. Then, since tests success is bound to time we can't guaranty test won't timeout on a specific workstation. For those you can't run tests under these limits we have no choice but to suggest the use of the `CI_TIMEOUT_MULTIPLIER` env variable.

**Comment by kevinpollet** [comment]
I also agree that we have to keep this multiplier because we cannot be sure that it will not be needed by someone or by the CI at some point. Btw, as other projects like Traefik use it, it's better to keep the behaviour to be consistent.
